export const types = {
    GET_FLIGHTS_DATA: 'GET_FLIGHTS_DATA',
    IS_LOADING: 'IS_LOADING',
    ON_GET_FLIGHTS_DATA_FAILURE:"ON_GET_FLIGHTS_DATA_FAILURE",
    ON_GET_FLIGHTS_DATA_FAILURE: 'ON_GET_FLIGHTS_DATA_FAILURE',
    SET_LOADING_REQUEST: 'SET_LOADING_REQUEST',

};